### ISSUE TITLE
Valetudo Conga in docker

### ISSUE THREAD

**Issue by carriopablo** [freeconga/Valetudo#7]
I'm trying to add Valetedudo Conga to my home assistant docker enverimonte. I've used this docker image [https://hub.docker.com/r/adrigzr/valetudo-conga/tags](url), as says this tutorial [https://domotuto.com/instalacion-valetudo-en-docker-para-robot-conga-3090-y-superiores/](url) but when running valetudo I get the error below. In the docker image, valeted seems to be built so I can't look up the source files.

```
valetudo         | [2022-03-29T19:34:19.520Z] [ERROR] unhandledRejection {
valetudo         |   reason: TypeError: Cannot read properties of null (reading 'toString')
valetudo         |       at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/common/linuxCapabilities/LinuxWifiConfigurationCapability.js:39:88)
valetudo         |       at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/cecotec/capabilities/CecotecWifiConfigurationCapability.js:13:32)
valetudo         |       at /snapshot/app/backend/lib/webserver/capabilityRouters/WifiConfigurationCapabilityRouter.js:10:44
valetudo         |       at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |       at next (/snapshot/app/node_modules/express/lib/router/route.js:137:13)
valetudo         |       at Route.dispatch (/snapshot/app/node_modules/express/lib/router/route.js:112:3)
valetudo         |       at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |       at /snapshot/app/node_modules/express/lib/router/index.js:281:22
valetudo         |       at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12)
valetudo         |       at next (/snapshot/app/node_modules/express/lib/router/index.js:275:10)
valetudo         |       at Function.handle (/snapshot/app/node_modules/express/lib/router/index.js:174:3)
valetudo         |       at router (/snapshot/app/node_modules/express/lib/router/index.js:47:12)
valetudo         |       at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |       at trim_prefix (/snapshot/app/node_modules/express/lib/router/index.js:323:13)
valetudo         |       at /snapshot/app/node_modules/express/lib/router/index.js:284:7
valetudo         |       at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12),
valetudo         |   stack: "TypeError: Cannot read properties of null (reading 'toString')\n" +
valetudo         |     '    at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/common/linuxCapabilities/LinuxWifiConfigurationCapability.js:39:88)\n' +
valetudo         |     '    at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/cecotec/capabilities/CecotecWifiConfigurationCapability.js:13:32)\n' +
valetudo         |     '    at /snapshot/app/backend/lib/webserver/capabilityRouters/WifiConfigurationCapabilityRouter.js:10:44\n' +
valetudo         |     '    at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)\n' +
valetudo         |     '    at next (/snapshot/app/node_modules/express/lib/router/route.js:137:13)\n' +
valetudo         |     '    at Route.dispatch (/snapshot/app/node_modules/express/lib/router/route.js:112:3)\n' +
valetudo         |     '    at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)\n' +
valetudo         |     '    at /snapshot/app/node_modules/express/lib/router/index.js:281:22\n' +
valetudo         |     '    at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12)\n' +
valetudo         |     '    at next (/snapshot/app/node_modules/express/lib/router/index.js:275:10)\n' +
valetudo         |     '    at Function.handle (/snapshot/app/node_modules/express/lib/router/index.js:174:3)\n' +
valetudo         |     '    at router (/snapshot/app/node_modules/express/lib/router/index.js:47:12)\n' +
valetudo         |     '    at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)\n' +
valetudo         |     '    at trim_prefix (/snapshot/app/node_modules/express/lib/router/index.js:323:13)\n' +
valetudo         |     '    at /snapshot/app/node_modules/express/lib/router/index.js:284:7\n' +
valetudo         |     '    at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12)',
valetudo         |   promise: Promise {
valetudo         |     <rejected> TypeError: Cannot read properties of null (reading 'toString')
valetudo         |         at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/common/linuxCapabilities/LinuxWifiConfigurationCapability.js:39:88)
valetudo         |         at CecotecWifiConfigurationCapability.getWifiStatus (/snapshot/app/backend/lib/robots/cecotec/capabilities/CecotecWifiConfigurationCapability.js:13:32)
valetudo         |         at /snapshot/app/backend/lib/webserver/capabilityRouters/WifiConfigurationCapabilityRouter.js:10:44
valetudo         |         at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |         at next (/snapshot/app/node_modules/express/lib/router/route.js:137:13)
valetudo         |         at Route.dispatch (/snapshot/app/node_modules/express/lib/router/route.js:112:3)
valetudo         |         at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |         at /snapshot/app/node_modules/express/lib/router/index.js:281:22
valetudo         |         at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12)
valetudo         |         at next (/snapshot/app/node_modules/express/lib/router/index.js:275:10)
valetudo         |         at Function.handle (/snapshot/app/node_modules/express/lib/router/index.js:174:3)
valetudo         |         at router (/snapshot/app/node_modules/express/lib/router/index.js:47:12)
valetudo         |         at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
valetudo         |         at trim_prefix (/snapshot/app/node_modules/express/lib/router/index.js:323:13)
valetudo         |         at /snapshot/app/node_modules/express/lib/router/index.js:284:7
valetudo         |         at Function.process_params (/snapshot/app/node_modules/express/lib/router/index.js:341:12)
valetudo         |   }
valetudo         | }
```

Any idea what could be the problem? Thank you.

**Comment by youssef88** [comment]
Hi!
I was facing the same issue while following the same tutorial...
For some reason, the config file for Valetudo in the tutorial has 
`"embedded": true`
Which [according to docs](https://valetudo.cloud/pages/development/building-and-modifying-valetudo.html), configures Valetudo for running locally in the conga. Just set it to false and it should run smoothly.

**Comment by gtrabanco** [comment]
If you want valetudo on Home assistant with Docker and run it in the Home Assistant you can use: https://github.com/freeconga/congatudo-add-on
